//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TrafficMonitorMedia.rc
//
#define IDD_OPTIONS_DIALOG              102
#define IDS_PLUGIN_NAME                 103
#define IDS_PLUGIN_DESCRIPTION          104
#define IDI_ICON1                       104
#define IDS_PLUGIN_ITEM_NAME            105
#define IDI_STATUS_PLAY_ON_DARK         106
#define IDI_STATUS_PLAY_ON_LIGHT        107
#define IDI_STATUS_PAUSE_ON_DARK        108
#define IDI_STATUS_PAUSE_ON_LIGHT       109
#define IDI_STATUS_NO_MEDIA_ON_DARK     110
#define IDI_STATUS_NO_MEDIA_ON_LIGHT    111
#define IDS_ACTION_NONE                 112
#define IDS_ACTION_TOGGLE_PLAY_PAUSE    113
#define IDS_ACTION_SKIP_NEXT            114
#define IDS_ACTION_SKIP_PREVIOUS        115
#define IDS_WHEEL_ACTION_NONE           116
#define IDS_WHEEL_ACTION_SWITCH_TRACK   117
#define IDS_WHEEL_ACTION_SWITCH_SESSION 118
#define IDS_WHEEL_ACTION_ADJUST_VOLUME  119
#define IDC_SHOW_PROGRESS_CHECK         1000
#define IDC_MAX_TITLE_WIDTH_EDIT        1001
#define IDC_MAX_TITLE_WIDTH_SPIN        1002
#define IDC_LEFT_CLICK_ACTION_COMBO     1003
#define IDC_LEFT_DOUBLE_CLICK_ACTION_COMBO 1004
#define IDC_RIGHT_CLICK_ACTION_COMBO    1005
#define IDC_SHOW_ARTIST_SECOND_LINE_CHECK 1008
#define IDC_SHOW_STATUS_ICON_CHECK      1009
#define IDC_SHOW_COVER_BACKGROUND_CHECK 1010
#define IDC_SMOOTH_COVER_SCALING_CHECK  1011
#define IDC_WHEEL_ACTION_COMBO          1012
#define IDC_SYSTEM_VOLUME_STEP_EDIT     1013
#define IDC_SYSTEM_VOLUME_STEP_SPIN     1014

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
