//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TrafficMonitorMedia.rc
//
#define IDD_OPTIONS_DIALOG              102
#define IDS_PLUGIN_NAME                 103
#define IDS_PLUGIN_DESCRIPTION          104
#define IDI_ICON1                       104
#define IDS_PLUGIN_ITEM_NAME            105
#define IDI_STATUS_PLAY_ON_DARK         106
#define IDI_STATUS_PLAY_ON_LIGHT        107
#define IDI_STATUS_PAUSE_ON_DARK        108
#define IDI_STATUS_PAUSE_ON_LIGHT       109
#define IDI_STATUS_NO_MEDIA_ON_DARK     110
#define IDI_STATUS_NO_MEDIA_ON_LIGHT    111
#define IDS_ACTION_NONE                 112
#define IDS_ACTION_TOGGLE_PLAY_PAUSE    113
#define IDS_ACTION_SKIP_NEXT            114
#define IDS_ACTION_SKIP_PREVIOUS        115
#define IDS_WHEEL_ACTION_NONE           116
#define IDS_WHEEL_ACTION_SWITCH_TRACK   117
#define IDS_WHEEL_ACTION_SWITCH_SESSION 118
#define IDS_WHEEL_ACTION_ADJUST_VOLUME  119
#define IDS_ACTION_OPEN_MEDIA_CARD      120
#define IDC_SHOW_PROGRESS_CHECK         1000
#define IDC_MAX_TITLE_WIDTH_EDIT        1001
#define IDC_MAX_TITLE_WIDTH_SPIN        1002
#define IDC_RIGHT_CLICK_ACTION_COMBO    1005
#define IDC_SHOW_ARTIST_SECOND_LINE_CHECK 1008
#define IDC_SHOW_STATUS_ICON_CHECK      1009
#define IDC_SHOW_COVER_BACKGROUND_CHECK 1010
#define IDC_SMOOTH_COVER_SCALING_CHECK  1011
#define IDC_WHEEL_ACTION_COMBO          1012
#define IDC_SYSTEM_VOLUME_STEP_EDIT     1013
#define IDC_SYSTEM_VOLUME_STEP_SPIN     1014
#define IDC_DISPLAY_GROUP               1015
#define IDC_MOUSE_ACTIONS_GROUP         1016
#define IDC_TITLE_WIDTH_LABEL_STATIC    1018
#define IDC_TITLE_WIDTH_UNIT_STATIC     1019
#define IDC_SYSTEM_VOLUME_LABEL_STATIC  1020
#define IDC_SYSTEM_VOLUME_UNIT_STATIC   1021
#define IDC_RIGHT_CLICK_LABEL_STATIC    1024
#define IDC_WHEEL_LABEL_STATIC          1025
#define IDC_RIGHT_CLICK_HINT_STATIC     1026
#define IDC_MIN_TITLE_WIDTH_LABEL_STATIC 1027
#define IDC_MIN_TITLE_WIDTH_EDIT        1028
#define IDC_MIN_TITLE_WIDTH_SPIN        1029
#define IDC_MIN_TITLE_WIDTH_UNIT_STATIC 1030
#define IDC_ICON_COLUMN_LABEL_STATIC 1031
#define IDC_TITLE_COLUMN_LABEL_STATIC 1032
#define IDC_ICON_LEFT_CLICK_LABEL_STATIC 1033
#define IDC_ICON_LEFT_CLICK_ACTION_COMBO 1034
#define IDC_ICON_LEFT_DOUBLE_CLICK_LABEL_STATIC 1035
#define IDC_ICON_LEFT_DOUBLE_CLICK_ACTION_COMBO 1036
#define IDC_TITLE_LEFT_CLICK_LABEL_STATIC 1037
#define IDC_TITLE_LEFT_CLICK_ACTION_COMBO 1038
#define IDC_TITLE_LEFT_DOUBLE_CLICK_LABEL_STATIC 1039
#define IDC_TITLE_LEFT_DOUBLE_CLICK_ACTION_COMBO 1040
#define IDC_LEFT_CLICK_DELAY_HINT_STATIC 1041

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
